### ISSUE TITLE
(Incomplete) No project in repo!

### ISSUE THREAD

**Issue by CharlesDLandau** [jjanenda/codecademy#1]
Your repository is empty, therefore your project cannot be reviewed! Please upload your Capstone to this repo and respond to this issue.

**Comment by jjanenda** [comment]
I don't understand. @sonny offered me a tee shirt cause my presentation was so good. Where's the disconnect?

**Comment by jjanenda** [comment]
[codeacademy_SQLfromScratch_Final_JohnJanenda.pdf](https://github.com/jjanenda/codecademy/files/2053680/codeacademy_SQLfromScratch_Final_JohnJanenda.pdf)
[codeacademy_SQLfromScratch_Final_JohnJanenda.pptx](https://github.com/jjanenda/codecademy/files/2053681/codeacademy_SQLfromScratch_Final_JohnJanenda.pptx)
[sql.code.txt](https://github.com/jjanenda/codecademy/files/2053682/sql.code.txt)

Files are re-attached here.  Don't know why Sonny Li could view them and offered me a free tee shirt, but they weren't in the repository.  Hope this clears it up.

**Comment by jjanenda** [comment]
@CharlesDLandau - does 'closing' the issue indicate that you have what you need from me so that you can review my project?  If so, when might I expect to hear back from you?  If not, please advise and I will do what I can to resolve.

**Comment by jjanenda** [comment]
@CharlesDLandau didn't get a response, but i see the issue.  I have 2 repositories.  The other one has the files.  It is here:  https://github.com/jjanenda/SQL_Scratch_Capstone_TurnIn_JJanenda.  Can you confirm that you have received the files one way or the other and that you will review in due time?

**Comment by CharlesDLandau** [comment]
Hi @jjanenda - I will review today!

**Comment by jjanenda** [comment]
Appreciated!  Glad we got that worked out.
